// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kalywehubxjmosxyxljz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthbHl3ZWh1YnhqbW9zeHl4bGp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMTEyNzUsImV4cCI6MjA3MDg4NzI3NX0.MEv_O8AWMhSikkYBnqkd6a0ufsnIxbzapQvqbhX3jq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});